apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: flask-hello-world
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flask-hello-world
    app.kubernetes.io/part-of: test-app-jxju
  name: flask-hello-world
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: flask-hello-world
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: flask-hello-world
    spec:
      containers:
      - image: quay.io/susdas_quay_org/build-e2e-atpw-tenant/test-app-jxju/flask-hello-world@sha256:4b496ad16bda173927873474ed65d0d8b358f84ef94b518b3c9be0d510231c6b
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
