apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: flask-hello-world
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flask-hello-world
    app.kubernetes.io/part-of: test-app-jxju
  name: flask-hello-worldeego
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: flask-hello-world
    weight: null
status: {}
